apiVersion: batch/v1beta1
kind: CronJob
metadata: 
  name: date
spec: 
  schedule: "*/1 * * * *" # runs every minute
  jobTemplate: 
    spec: 
      template: 
        spec: 
          containers: 
          - name: date
            image: busybox
            args: 
            - /bin/sh
            - -c
            - date; 
          restartPolicy: OnFailure
